### PR TITLE
Test refactor

### PR DESCRIPTION
**Pull request by susan-garry**
I made use of the new turnt feature to clean up the testing process:
- Node depth tests are in `test/depth`
- Node depth tests expect `.og` files instead of `.gfa` files; no longer generate `.og` files for each test

To easily create a testing process for another odgi subcommand, one can now run
`cp -r test/depth test/<new-command>`
and edit the `turnt.toml` files accordingly.

### CODE REVIEW

**Review by sampsyo — APPROVED** [review]
Yay; this looks super great!! I'm glad we're able to save some of the test-config complexity this way.

**Comment by susan-garry** [comment]
Having fewer files floating around is good for the soul.

I just added a "Testing" section to the README to clarify how to install the latest, in-development version of turnt.

**Comment by sampsyo** [comment]
The README section looks great!

**Comment by susan-garry** [comment]
That's great! Better to deal with this now than find out the README is out of date a few months down the line.

**Pull request merged**
